### ISSUE TITLE
給Makeblock的一封信

### ISSUE THREAD

**Issue by da112601** [MakeblockMacau/Mission#8]
最新版草稿由 @csroychan 提供
--------------

##中文版
主旨: 申請MAKEBLOCK澳門批發商認證

2016年12月X日
深圳市創客工場科技有限公司
總經理

本司"澳門新奇科技有限公司 (FANTASTIC TECNOLOGY COMPANY LTD.)"‚  於2014年在澳門成立, 公司成立目的是自主開發及推動一個澳門網購電商平台 ------“澳門捷購” http://www.jezzco.com. 經過二年多的研究發展,現時"澳門捷購"已成為澳門本地其中一個主要銷售兒童及母嬰用品的網購平台.

近年, 了解到社會發展趨勢,推動教育理念發展實為大勢所趨. 有見及此,本公司研究參考全球對兒童科技及創新教育發展S.T.E.M的推行計劃, 從中得悉鄰埠地區香港及內地正使用MAKEBLOCK作為推行S.T.E.M教育課程的必要教材. 該教材的主要推廣對象為兒童, 課程設計較為淺易掌握, 由淺入深, 並加入一系列的比賽活動激發學童的創新設計概念.

由於本公司擁有兒童玩具網購經驗, 且與澳門本地的兒童教育中心合作, 計劃於2017年共同向澳門特別行政區政府申請成立"澳門S.T.E.M科技創新教育學會". 該學會將集合科技, 教育, 學會三家機構相互合作, 秉承推動科技發展的理念.

基於上述原因,現籍此函希望得到MAKEBLOCK官方認可和協助, 給予 "澳門新奇科技有限公司" 成為澳門首家持有MAKEBLOCK 批發商認證. 盼貴司能給予本公司機會, 本公司可隨後安排團隊前往深圳MAKEBLOCK總部進行洽談事宜.

台祺

澳門新奇科技有限公司團隊 敬上

##英文版
Subject: Application for Macau MAKEBLOCK wholesale distributor license

Dear Sirs,

We have the pleasure of introducing ourselves to you as one of the most reputable e-commerce website in Macau "Macau Jezzco" http://www.jezzco.com. Our company, "Fantastic Technology Company Ltd, was set up in 2014 in Macau. Through protracted and unremitting efforts during the last 2 years, Macau Jezzco has become the major sale platform of Maternal Infant Care Products in Macau.

With the development of society during these years, exploring education development is given a vigorous boost. Hence, our company study and examine the S.T.E.M plan. We knew that Hong Kong and Mainland China have been using MAKEBLOCK as the specialized teaching materials to S.T.E.M. The course is mainly intended to all children. As to the organization of curriculum contents, the principles of sequence is proceeding from the simple to the more complex and from the easiness to the difficult, then adding a series of match or activities to arouse student's creativity on computer science design.

Since our company has e-commerce experience on selling children goods and we also have corporation with several Macau local children education centers, we have planned to set up the "Macau S.T.E.M Technology Association" in 2017. The establishment of the association is targeted to push the Macau technology development.

In the connection, we would to have the authorization and assistance from MAKEBLOCK being the first wholesale distributor in Macau. We truly appreciate if you may seriously consider our request. We could set up an appointment and arrange for our partner to be present at the meeting in MAKEBLOCK head office.

Thank you very much for your attention, and look forward to hearing from you soon.

**Comment by kwanterry1213** [comment]
致 MAKEBLOCK
本司"澳門新奇科技有限公司 FANTASTIC TECNOLOGY COMPANY LTD."
於2014年冬成立, “澳門捷購” http://www.jezzco.com. 網購電商平台, 目標市場 - 母嬰用品

了解到現時全球對幼兒S.T.E.M的興起, 可望在未來成為主流教育的趨勢, 而參考MAKEBLOCK在香港及內地的成功案例, 我們發現通過MAKEBLOCK能比較容易啓發兒童在S.T.E.M方面的思維, 因此我們選擇MAKEBLOCK. 

本司計劃於澳門特別行政區政府申請並成立"澳門S.T.E.M科技創新教育學會", 在得倒政府支持的同時大力發展MAKEBLOCK及S.T.E.M.理念. 我們訂制課程, 執教及結合電商平台進行零售及推廣, 相信能為MAKEBLOCK及澳門S.T.E.M 帶來正面影響.

籍此希望能得MAKEBLOCK支持, 或提供成為澳門區總代理條件. 本司亦歡迎安排團隊前往深圳MAKEBLOCK總部進行洽談事宜.

台祺
澳門新奇科技有限公司團隊 敬上

**Comment by da112601** [comment]
主旨: 申請MAKEBLOCK澳門批發商認證

2016年12月X日
深圳市創客工場科技有限公司
總經理


本司"澳門新奇科技有限公司 (FANTASTIC TECNOLOGY COMPANY LTD.)"‚  於2014年在澳門成立, 公司成立目的是自主開發及推動一個澳門網購電商平台 ------“澳門捷購” http://www.jezzco.com. 經過二年多的研究發展,現時"澳門捷購"已成為澳門本地其中一個主要銷售兒童及母嬰用品的網購平台.

近年, 了解到社會發展趨勢,推動教育理念發展實為大勢所趨. 有見及此,本公司研究參考全球對兒童科技及創新教育發展S.T.E.M的推行計劃, 從中得悉鄰埠地區香港及內地正使用MAKEBLOCK作為推行S.T.E.M教育課程的必要教材. 該教材的主要推廣對象為兒童, 課程設計較為淺易掌握, 由淺入深, 並加入一系列的比賽活動激發學童的創新設計概念.

由於本公司擁有兒童玩具網購經驗, 且與澳門本地的兒童教育中心合作, 計劃於2017年共同向澳門特別行政區政府申請成立"澳門S.T.E.M科技創新教育學會". 該學會將集合科技, 教育, 學會三家機構相互合作, 秉承推動科技發展的理念.

基於上述原因,現籍此函希望得到MAKEBLOCK官方認可和協助, 給予 "澳門新奇科技有限公司" 成為澳門首家持有MAKEBLOCK 批發商認證. 盼貴司能給予本公司機會, 本公司可隨後安排團隊前往深圳MAKEBLOCK總部進行洽談事宜.

台祺

澳門新奇科技有限公司團隊 敬上

**Comment by kwanterry1213** [comment]
山火竹弓戈

**Comment by da112601** [comment]
已更新最新版本

**Comment by mailman724** [comment]
主旨: 申請成為MAKEBLOCK產品系列的澳門總代理

致：深圳市創客工場科技有限公司
總經理台啟

本司"澳門新奇科技有限公司 FANTASTIC TECNOLOGY COMPANY LTD." 於2014年冬成立，現主要營運網購電商平台, 目標市場為母嬰兒童用品。經過二年多的發展,現時已成為澳門本地其中一個主要銷售兒童及母嬰用品的網購平台.

了解到近年社會對S.T.E.M教育的需求及發展趨勢，參考鄰近地區例如香港及內地正全力推行S.T.E.M教育課程，本公司有意在澳門投入資源推動S.T.E.M相關的教育課程，而經過巿場調查及研究後，發現貴公司MAKEBLOCK系列的產品非常合適應用在S.T.E.M教育範疇，亦附合本公司的推廣策略。

本公司有意在澳門開辦教育中心全面推行以MAKEBLOCK為主的課程，及後再推廣至全澳門的中，小及大學，以及向政府爭取資源在澳門推廣S.T.E.M教育。

基於上述原因，特此致函貴公司申請成為MAKEBLOCK產品系列的澳本總代理，以便展開相關業務。

台祺

澳門新奇科技有限公司團隊
電話:

**Comment by da112601** [comment]
已寄出, 多留意
jezzcoshop@gmail.com 或admin@jezzco.com
